In [1]:

import pandas as pd
import numpy as np
from sklearn import preprocessing

In [3]:

col=["duration","protocol_type","service","flag","src_bytes","dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins","logged_in","num_compromised","root_shell","su_attempted","num_root","num_file_creations","num_shells","num_access_files","num_outbound_cmds","is_host_login","is_guest_login","count","srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count","dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate","dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate","dst_host_rerror_rate","dst_host_srv_rerror_rate","label"] 
col1=list('duration protocol_type service flag src_bytes dst_bytes land wrong_fragment urgent hot num_failed_logins logged_in num_compromised root_shell su_attempted num_root num_file_creations num_shells num_access_files num_outbound_cmds is_host_login is_guest_login count srv_count serror_rate srv_serror_rate rerror_rate srv_rerror_rate same_srv_rate diff_srv_rate srv_diff_host_rate dst_host_count dst_host_srv_count dst_host_same_srv_rate dst_host_diff_srv_rate dst_host_same_src_port_rate dst_host_srv_diff_host_rate dst_host_serror_rate dst_host_srv_serror_rate dst_host_rerror_rate dst_host_srv_rerror_rate label') 


data_train= pd.read_csv('C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/KDDTrain+.txt', sep=',', names= col,header=None)
data_test=pd.read_csv('C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/KDDTest+.txt', sep=',', names= col,header=None)
print(data_train.shape)
print(data_test.shape)

(125973, 42)
(22544, 42)


In [4]:
df= pd.concat([data_train, data_test])
print(df.shape)
#total [148516 rows x 42 columns]

(148517, 42)


In [6]:

# one hot encode the label with sklearn label encoder 
df_label=df.label
df_label=df.label[:125973]
print(df_label.shape)

le= preprocessing.LabelEncoder()
le.fit(df_label)
print(le.classes_)
a= le.transform(df_label) 
print(a)
tra= pd.DataFrame(a)
enc = preprocessing.OneHotEncoder()
enc.fit(tra)
onehotlabels = enc.transform(tra).toarray()
onehotlabels.shape

np.savetxt('C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/label_encoded_train.csv', onehotlabels, fmt='%.18e', delimiter=',', newline='\n', header='', footer='', comments='# ')

(125973,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[20 15 19 ... 18 20 21]


C:\Users\mkahs\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [7]:
df_label_test=df.label[125973:]
print(df_label_test.shape)
#print(df_label_test)
le1= preprocessing.LabelEncoder()
le1.fit(df_label_test)
a1= le1.transform(df_label_test) 
print(a1)
tra_test= pd.DataFrame(a1)

enc1 = preprocessing.OneHotEncoder()
enc1.fit(tra_test)
onehotlabels1 = enc1.transform(tra_test).toarray()
onehotlabels1.shape
np.savetxt('C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/label_encoded_test.csv', onehotlabels1, fmt='%.18e', delimiter=',', newline='\n', header='', footer='', comments='# ')

(22544,)
[21 21 21 ... 15 21 14]


C:\Users\mkahs\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [11]:
new_df= df.drop(labels=["num_outbound_cmds","label"],axis=1)
for i in range(len(new_df.columns)):
    count = i+0
    name = new_df.columns[count]
    if name== 'protocol_type' :
        le = preprocessing.LabelEncoder()
        le.fit(new_df[name])
        a= le.transform(new_df[name])
        x= np.reshape(a,(-1,1))
        new1= np.asarray(x).reshape(1, -1)[0,:]
        new_df1= pd.DataFrame({'protocol_type': new1})
        new_df.update(new_df1, overwrite= True)
        #print(data)
        print('Protocol_type')
        #print(x)
    elif name=='service' :
        le = preprocessing.LabelEncoder()
        le.fit(new_df[name])
        b= le.transform(new_df[name])
        y= np.reshape(b,(-1,1))
        new2= np.asarray(y).reshape(1, -1)[0,:]
        new_df2= pd.DataFrame({'service': new2})
        new_df.update(new_df2, overwrite= True)
        #print('Service')
        #print(y)
    elif name=='flag':
        le = preprocessing.LabelEncoder()
        le.fit(new_df[name])
        c= le.transform(new_df[name])
        z= np.reshape(c,(-1,1))
        new3= np.asarray(z).reshape(1, -1)[0,:]
        new_df3= pd.DataFrame({'flag': new3})
        new_df.update(new_df3, overwrite= True)
        #print(data)
       # print('flag')
        #print(z)
        # Min-max normaliztion on dataframe

g= new_df.sub(new_df.min(axis=0))
h= (new_df.max(axis=0)).sub(new_df.min(axis=0))
f= g.div(h)

#print(f)

np.savetxt('C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/train_test_without_miss_normalize.csv', f, fmt='%.18e', delimiter=',', newline='\n', header='', footer='', comments='# ')

Protocol_type


TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [10]:
disct_df= pd.read_csv('C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/train_test_with_misslabel.csv', sep=',',header=None)

FileNotFoundError: [Errno 2] File b'C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/train_test_with_misslabel.csv' does not exist: b'C:/Users/mkahs/Network-Intrusion_detection/Network-Intrusion-Detection/train_test_with_misslabel.csv'