In [1]:
import numpy as np
import pandas as pd
pd.pandas.set_option('display.max_columns', None)


X_train = pd.read_csv('X_train.csv')
X_test = pd.read_csv('X_test.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((125973, 123), (22544, 123), (125973, 1), (22544, 1))

In [2]:
selected_features = ['dst_host_srv_count','dst_host_same_srv_rate','dst_host_serror_rate','src_bytes'
                     ,'dst_host_diff_srv_rate','count','logged_in','dst_host_srv_diff_host_rate'
                     ,'diffic','dst_host_same_src_port_rate','dst_host_count'
                     ,'duration','root_shell','service_http','flag_SF','dst_host_rerror_rate']

X_train = X_train[selected_features]
X_test = X_test[selected_features]

In [3]:

import matplotlib.pyplot as plt

import sklearn
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [4]:
from sklearn import preprocessing

scaler_train = preprocessing.StandardScaler().fit(X_train)
X_train1=scaler_train.transform(X_train)
scaler_test = preprocessing.StandardScaler().fit(X_test)
X_test1=scaler_test.transform(X_test)

y_test=y_test['class']


print(X_train1.std(axis=0))
print(X_test1.std(axis=0))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
from sklearn.linear_model import LogisticRegression

clf=DecisionTreeClassifier(random_state=0)

clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [6]:
clf.predict(X_test)
clf.predict(X_test)[0:10]

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [7]:
y_pred = clf.predict(X_test)

pd.crosstab(y_test,y_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0      1
Actual attacks                
0                  9296    415
1                  2805  10028

In [8]:
from sklearn.model_selection import cross_val_score
from sklearn import metrics
accuracy = cross_val_score(clf, X_test, y_test, cv=10, scoring='accuracy')
print("Accuracy: %0.5f (+/- %0.5f)" % (accuracy.mean(), accuracy.std() * 2))
precision = cross_val_score(clf, X_test, y_test, cv=10, scoring='precision')
print("Precision: %0.5f (+/- %0.5f)" % (precision.mean(), precision.std() * 2))
recall = cross_val_score(clf, X_test, y_test, cv=10, scoring='recall')
print("Recall: %0.5f (+/- %0.5f)" % (recall.mean(), recall.std() * 2))
f = cross_val_score(clf, X_test, y_test, cv=10, scoring='f1')
print("F-measure: %0.5f (+/- %0.5f)" % (f.mean(), f.std() * 2))

Accuracy: 0.99512 (+/- 0.00159)
Precision: 0.99548 (+/- 0.00151)
Recall: 0.99595 (+/- 0.00318)
F-measure: 0.99571 (+/- 0.00140)
